// Articles
export const GET_BANNERS_REQUEST = 'article/GET_BANNERS_REQUEST';
export const GET_BANNERS_SUCCESS = 'article/GET_BANNERS_SUCCESS';
export const GET_BANNERS_FAILURE = 'article/GET_BANNERS_FAILURE';

export const GET_ARTICLES_REQUEST = 'article/GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'article/GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'article/GET_ARTICLES_FAILURE';
